#include <stdio.h>

/**
 * Multiples of 3 and 5
 * If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
 * The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
 */
void problem1(){
    int somaDosMultiplos = 0;
    for (int i = 1; i < 1000; ++i) {

        //se o resto da divisão de i por 3 ou 5 for diferente de 0
        if(((i % 3) == 0) || ((i % 5) == 0) ){
            somaDosMultiplos += i;
        }
    }

    printf("Problema 1: %d", somaDosMultiplos);
}

/**
 * Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
void problem2(){

    int n1 = 1;
    int n2 = 2;
    int soma = n2;
    for (int i = 3; n2 < 4000000; ++i) {
        int ni = n1 + n2;
        if((ni % 2) == 0) soma += ni;
        n1 = n2;
        n2 = ni;
    }
    printf("Problema 2: %d", soma);
}

/**
 * Largest prime factor
 * The prime factors of 13195 are 5, 7, 13 and 29.
 * What is the largest prime factor of the number 600851475143 ?
 */
void problem3(){
    int maiorFator = 0;
    long base = 600851475143;
    long baseAux = base;
    for (long i = 2; i <= baseAux;) {
        float fator = baseAux % i;
        if(fator == 0 ){
            baseAux = baseAux / i;
            //printf("%d \n", i);
            if (i > maiorFator) maiorFator = (int) i;
        }else{
            ++i;
        }
    }

    printf("Problema 3: %d", maiorFator);
}


int main() {
    printf("Hello, World!\n");
    //problem1();
    //problem2();
    problem3();

    return 0;
}



